# Generated by Django 5.0.3 on 2024-03-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('product_materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterials',
            name='material',
        ),
        migrations.AlterField(
            model_name='productmaterials',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='productmaterials',
            name='material',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='materials.materials'),
            preserve_default=False,
        ),
    ]
