# Generated by Django 5.0.3 on 2024-03-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('product_materials', '0002_remove_productmaterials_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
