# Generated by Django 5.0.3 on 2024-03-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('product_materials', '0003_alter_productmaterials_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
