# Generated by Django 5.0.3 on 2024-03-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('product_materials', '0004_alter_productmaterials_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productmaterials',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
