# Generated by Django 5.0.3 on 2024-03-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_materials', '0005_alter_productmaterials_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
