# Generated by Django 5.0.3 on 2024-03-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('warehouses', '0002_alter_warehouses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouses',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_warehouse', to='materials.materials'),
        ),
        migrations.AlterField(
            model_name='warehouses',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
